### PR TITLE
data structures

### LINKED ISSUE #7: Basic data structures

### PR DESCRIPTION
**Pull request by julienchastang**
closes #7

### CODE REVIEW

**Comment by dopplershift** [comment]
We should probably talk about this at tomorrow's meeting. One question comes to mind: what made you pick a raw markdown file rather than a notebook?

**Comment by julienchastang** [comment]
It is simple enough to convert the markdown to a Jupyter Notebook and probably a good idea so that we can integrate the code with the Python tool chain (code formatting, static analysis, maybe testing, etc.). This is a minor issue for the data structures notebook, but will be more important down the line (e.g., the numpy section), so it would be good to get this worked out now.

But how will the notebooks integrate with the rest of the gh-pages branch? Which branch should the notebooks live so that we can have our tool chain (travis, mybinder etc.) similar to what we have for the Unidata Python Workshop. Or should we check the notebooks into the Unidata Python Workshop repository so that we can build/beef up our training material and simply link to them from the OTP gh-pages branch? This option would allow for a lot of training material that could be picked and chosen from for various training workshops (regional versus local, 1 day versus 3 day, etc.). And we could leverage the CI stuff you've already set up on Unidata Python Workshop repo.

**Comment by dopplershift** [comment]
I've put one notebook on the master branch, and that's where I was planning on putting the rest.  Long term, we need to figure out if there's a good way to unify all of this notebook-based material, but I'm content to make that something to tackle later.

**Comment by julienchastang** [comment]
Superseded by #67

**Pull request closed without merging**
