### PR TITLE
Update introduction.md

### PR DESCRIPTION
**Pull request by lago8103**
The only sentence that threw me off was "The technology was generalized to allow for programming language "back-ends" to be plugged into the notebooks." 

Is this sentence necessary? I am not quite sure what it means. Other than that, this is a great introduction! Especially liked the bullet points for the pragmatic reasons why python excels as a coding language and the mention of stackoverflow.com.

### CODE REVIEW

**Comment by julienchastang** [comment]
Before merging, let me just clean up the superfluous diffs.

**Comment by dopplershift** [comment]
Also need to address the question @lago8103 raised--That sentence doesn't seem like something readily parsed by someone not already familiar with this stuff.

**Comment by julienchastang** [comment]
Never mind about the superfluous diffs (there are none), but I still want to workshop a couple of items with @lago8103 in person before merging. Thxs.

**Comment by julienchastang** [comment]
@lago8103 and I are done workshopping this file

**Comment by julienchastang** [comment]
OK, I cleaned up a few items that I forgot to address when we workshopped this file including "technology was generalized..." section. @lago8103 are we good?

**Pull request merged**
